### ISSUE TITLE
Can't install the Output part.  

### ISSUE THREAD

**Issue by brak265** [pavelzw/calibre-kindle-comics#12]
I can't seem to get the output plugin to work.  I unzipped the file, put the kindlegen in the folder, rezipped it, and then I get this error when trying to install:

calibre, version 5.34.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in '/Users/0000000000/Downloads/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.34  embedded-python: True is64bit: True
macOS-10.16-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '21.1.0', 'Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101')
Python 3.8.5
OSX: ('10.16', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: Gather KFX-ZIP (from KFX Input) (1, 46, 0) && DeDRM (7, 2, 1) && Package KFX (from KFX Input) (1, 46, 0) && EpubMerge (2, 11, 0) && KFX metadata reader (from KFX Input) (1, 46, 0) && KFX Input (1, 46, 0) && Set KFX metadata (from KFX Output) (1, 58, 0) && KFX Output (1, 58, 0) && Quality Check (1, 11, 4) && Kindle Comics Input (0, 0, 2)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 476, in add_plugin
  File "calibre/customize/ui.py", line 64, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/Users/0000000000/Downloads/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

**Comment by LarsOlt** [comment]
Make sure the files are at the top level of the zip and not in a folder.

**Comment by rahulonmars** [comment]
same error..unable to install.. __init__.py is present in the zip and not inside any folder.. still doesn't work

**Comment by Tomas622** [comment]
Has anyone solved this issue?

**Comment by PlanetPhilip** [comment]
The problem is that, when u unzip and rezip like normal, the file structure is changed from 

**THIS:** 
```
├── Kindle Comics Output.zip
│   ├── build_file.py
│   ├── __init__.py
│   ├── kindlegen
│   └── plugin-import-name-kindle_comics_output.txt
```

**to THIS:**
```
├── Kindle Comics Output.zip
│   ├── Kindle Comics Output
│   │   ├── build_file.py
│   │   ├── __init__.py
│   │   ├── kindlegen
│   │   └── plugin-import-name-kindle_comics_output.txt

```

which creates an extra folder and ruins the file structure, breaking the plugin.
Instead, you need to zip it using a different method that preserves the original structure.


**SOLUTION:**
```
# 0. Open Terminal, and run the following command

# 1. Replace with the folder where your files are
zip -j "/path/to/Kindle Comics Output.zip" "/path/to/kindlegen"
```
