### ISSUE TITLE
Invalid Output Plugin

### ISSUE THREAD

**Issue by Bouilloire-dot** [pavelzw/calibre-kindle-comics#5]
Hello! Thank you so much for developing this plugin!

Following your instructions, I was able to install the `Kindle Comics Input.zip` but when I try to install the `Kindle Comics Output.zip`, Calibre return this error :

```
calibre, version 5.17.0
ERREUR : Exception non gérée: <b>InvalidPlugin</b>:The plugin in '/home/user/downloads/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

calibre 5.17  embedded-python: True is64bit: True
Linux-5.8.0-50-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.8.0-50-generic', '#56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021')
Python 3.8.5
Interface language: fr
Successfully initialized third party plugins: Kindle Comics Input (0, 0, 2)
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 327, in add_plugin
  File "calibre/customize/ui.py", line 477, in add_plugin
  File "calibre/customize/ui.py", line 65, in load_plugin
  File "calibre/customize/zipplugin.py", line 284, in load
  File "calibre/customize/zipplugin.py", line 379, in _locate_code
calibre.customize.InvalidPlugin: The plugin in '/home/user/downloads/calibre_kindle_comics/Kindle Comics Output.zip' is invalid. It does not contain a top-level __init__.py file

```

The Output.zip has this structure : 

```
├── Kindle Comics Output.zip
│   ├── build_file.py
│   ├── __init__.py
│   ├── kindlegen
│   └── plugin-import-name-kindle_comics_output.txt
```

The `__init__.py` is here so what did I do wrong? :/
Thank you for your help!

**Comment by Bouilloire-dot** [comment]
Well actually I made a mistake during the zip compression and the zip's structure was :

```
├── Kindle Comics Output.zip
│   ├── Kindle Comics Output
│   │   ├── build_file.py
│   │   ├── __init__.py
│   │   ├── kindlegen
│   │   └── plugin-import-name-kindle_comics_output.txt
```

Everything works fine now ^^"
Sorry for the bothering!
