### ISSUE TITLE
Manga conversion fails

### ISSUE THREAD

**Issue by Bouilloire-dot** [pavelzw/calibre-kindle-comics#6]
Hi! I just tried my first conversion from cbz to mobi but it keeps failng, returning this. What can I do please?

```
calibre, version 5.17.0 (linux, embedded-python: True)
Erreur lors de la conversion: Échoué: Conversion du livre 1 sur 1 (Lorsque nous vivions ensemble - Vol. 1)

Conversion du livre 1 sur 1 (Lorsque nous vivions ensemble - Vol. 1)
Conversion options changed from defaults:
  cover: '/tmp/calibre_5.17.0_tmp_i78zl28a/2wt5dbaz.jpeg'
  manga: True
  output_profile: 'kindle_pw3'
  read_metadata_from_opf: '/tmp/calibre_5.17.0_tmp_i78zl28a/g9vy4x_d.opf'
  verbose: 2
Resolved conversion options
calibre version: 5.17.0
{'asciiize': False,
 'author_sort': None,
 'authors': None,
 'base_font_size': 0.0,
 'book_producer': None,
 'change_justification': 'original',
 'chapter': "//*[((name()='h1' or name()='h2') and re:test(., "
            "'\\s*((chapter|book|section|part)\\s+)|((prolog|prologue|epilogue)(\\s+|$))', "
            "'i')) or @class = 'chapter']",
 'chapter_mark': 'pagebreak',
 'comments': None,
 'cover': '/tmp/calibre_5.17.0_tmp_i78zl28a/2wt5dbaz.jpeg',
 'debug_pipeline': None,
 'dehyphenate': True,
 'delete_blank_paragraphs': True,
 'disable_font_rescaling': False,
 'dont_compress': False,
 'duplicate_links_in_toc': False,
 'embed_all_fonts': False,
 'embed_font_family': None,
 'enable_heuristics': False,
 'expand_css': False,
 'extra_css': None,
 'extract_to': None,
 'filter_css': '',
 'fix_indents': True,
 'font_size_mapping': None,
 'format_scene_breaks': True,
 'gamma': '1.0',
 'html_unwrap_factor': 0.4,
 'input_encoding': None,
 'input_profile': <calibre.customize.profiles.InputProfile object at 0x7f3cf8e68460>,
 'insert_blank_line': False,
 'insert_blank_line_size': 0.5,
 'insert_metadata': False,
 'isbn': None,
 'italicize_common_cases': True,
 'keep_ligatures': False,
 'language': None,
 'level1_toc': None,
 'level2_toc': None,
 'level3_toc': None,
 'line_height': 0.0,
 'linearize_tables': False,
 'manga': True,
 'margin_bottom': 5.0,
 'margin_left': 5.0,
 'margin_right': 5.0,
 'margin_top': 5.0,
 'margins': 'auto',
 'markup_chapter_headings': True,
 'max_height': '1680',
 'max_toc_links': 50,
 'max_width': '1264',
 'minimum_line_height': 120.0,
 'mobi_file_type': 'old',
 'mobi_ignore_margins': False,
 'mobi_keep_original_images': False,
 'mobi_toc_at_start': False,
 'no_chapters_in_toc': False,
 'no_greyscale': False,
 'no_inline_navbars': True,
 'no_inline_toc': False,
 'output_profile': <calibre.customize.profiles.KindlePaperWhite3Output object at 0x7f3cf8e68af0>,
 'page_breaks_before': "//*[name()='h1' or name()='h2']",
 'personal_doc': '[PDOC]',
 'prefer_author_sort': False,
 'prefer_metadata_cover': False,
 'pretty_print': False,
 'pubdate': None,
 'publisher': None,
 'rating': None,
 'read_metadata_from_opf': '/tmp/calibre_5.17.0_tmp_i78zl28a/g9vy4x_d.opf',
 'remove_fake_margins': True,
 'remove_first_image': False,
 'remove_paragraph_spacing': False,
 'remove_paragraph_spacing_indent_size': 1.5,
 'renumber_headings': True,
 'replace_scene_breaks': '',
 'search_replace': '[]',
 'series': None,
 'series_index': None,
 'share_not_sync': False,
 'smarten_punctuation': False,
 'sr1_replace': None,
 'sr1_search': None,
 'sr2_replace': None,
 'sr2_search': None,
 'sr3_replace': None,
 'sr3_search': None,
 'start_reading_at': None,
 'subset_embedded_fonts': False,
 'tags': None,
 'timestamp': None,
 'title': None,
 'title_sort': None,
 'toc_filter': None,
 'toc_threshold': 6,
 'toc_title': None,
 'transform_css_rules': '[]',
 'unsmarten_punctuation': False,
 'unwrap_lines': True,
 'use_auto_toc': False,
 'verbose': 2,
 'webtoon': False}
InputFormatPlugin: Kindle Comics Input running
on /tmp/calibre_5.17.0_tmp_i78zl28a/17gerekl.cbz
{'manga': True, 'webtoon': False, 'margins': 'auto', 'no_greyscale': False, 'max_width': 1264, 'max_height': 1680, 'black_borders': False, 'white_borders': False, 'bordersColor': None, 'profileData': ('Kindle Paperwhite 3/4/Voyage/Oasis', (1264, 1680), [0, 0, 0, 17, 17, 17, 34, 34, 34, 51, 51, 51, 68, 68, 68, 85, 85, 85, 102, 102, 102, 119, 119, 119, 136, 136, 136, 153, 153, 153, 170, 170, 170, 187, 187, 187, 204, 204, 204, 221, 221, 221, 238, 238, 238, 255, 255, 255], 1.8), 'profile': 'KV', 'hq': False, 'forcecolor': False, 'forcepng': False, 'gamma': 1.0, 'stretch': False, 'kfx': False, 'upscale': False, 'format': 'MOBI', 'cropping': 2, 'croppingp': 1.0, 'splitter': 0, 'iskindle': True, 'panelview': True, 'covers': [], 'autoscale': False, 'righttoleft': True, 'summary': '', 'authors': ['unknown'], 'chapters': False, 'batchsplit': 1, 'customheight': 0, 'customwidth': 0, 'output': None, 'title': 'defaulttitle'}
Extracting images.
Extracted images into /tmp/calibre_5.17.0_tmp_i78zl28a/e5mq8tsb_comic_extract
Moved images to structure in /tmp/calibre_5.17.0_tmp_i78zl28a/2oi31ktk_oebps
Processing images.
Processing file00648.jpg
Processing file00083.jpg
Processing file00355.jpg
Processing file00464.jpg
Processing file00681.jpg
Processing file00595.jpg
Processing file00598.jpg
Processing file00624.jpg
Processing file00605.jpg
Processing file00148.jpg
Processing file00475.jpg
Processing file00131.jpg
Processing file00107.jpg
Processing file00383.jpg
Processing file00438.jpg
Processing file00234.jpg
Processing file00169.jpg
Processing file00705.jpg
Processing file00232.jpg
Processing file00542.jpg
Processing file00670.jpg
Processing file00174.jpg
Processing file00239.jpg
Processing file00218.jpg
Processing file00042.jpg
Processing file00186.jpg
Processing file00192.jpg
Processing file00547.jpg
Processing file00090.jpg
Processing file00058.jpg
Processing file00333.jpg
Processing file00178.jpg
Processing file00157.jpg
Processing file00315.jpg
Processing file00647.jpg
Processing file00263.jpg
Processing file00164.jpg
Processing file00690.jpg
Processing file00544.jpg
Processing file00562.jpg
Processing file00251.jpg
Processing file00221.jpg
Processing file00189.jpg
Processing file00506.jpg
Processing file00167.jpg
Processing file00375.jpg
Processing file00142.jpg
Processing file00549.jpg
Processing file00052.jpg
Processing file00524.jpg
Processing file00085.jpg
Processing file00555.jpg
Processing file00399.jpg
Processing file00473.jpg
Processing file00537.jpg
Processing file00078.jpg
Processing file00607.jpg
Processing file00144.jpg
Processing file00252.jpg
Processing file00534.jpg
Processing file00418.jpg
Processing file00337.jpg
Processing file00120.jpg
Processing file00526.jpg
Processing file00404.jpg
Processing file00002.jpg
Processing file00372.jpg
Processing file00080.jpg
Processing file00201.jpg
Processing file00312.jpg
Processing file00161.jpg
Processing file00667.jpg
Processing file00671.jpg
Processing file00147.jpg
Processing file00459.jpg
Processing file00268.jpg
Processing file00018.jpg
Processing file00223.jpg
Processing file00665.jpg
Processing file00062.jpg
Processing file00432.jpg
Processing file00244.jpg
Processing file00401.jpg
Processing file00200.jpg
Processing file00231.jpg
Processing file00358.jpg
Processing file00114.jpg
Processing file00658.jpg
Processing file00212.jpg
Processing file00462.jpg
Processing file00461.jpg
Processing file00303.jpg
Processing file00645.jpg
Processing file00597.jpg
Processing file00551.jpg
Processing file00311.jpg
Processing file00245.jpg
Processing file00442.jpg
Processing file00582.jpg
Processing file00165.jpg
Processing file00603.jpg
Processing file00541.jpg
Processing file00579.jpg
Processing file00495.jpg
Processing file00633.jpg
Processing file00009.jpg
Processing file00217.jpg
Processing file00498.jpg
Processing file00643.jpg
Processing file00154.jpg
Processing file00530.jpg
Processing file00184.jpg
Processing file00272.jpg
Processing file00637.jpg
Processing file00521.jpg
Processing file00294.jpg
Processing file00053.jpg
Processing file00696.jpg
Processing file00330.jpg
Processing file00490.jpg
Processing file00187.jpg
Processing file00299.jpg
Processing file00321.jpg
Processing file00571.jpg
Processing file00417.jpg
Processing file00623.jpg
Processing file00484.jpg
Processing file00301.jpg
Processing file00492.jpg
Processing file00123.jpg
Processing file00380.jpg
Processing file00548.jpg
Processing file00635.jpg
Processing file00368.jpg
Processing file00613.jpg
Processing file00229.jpg
Processing file00674.jpg
Processing file00230.jpg
Processing file00342.jpg
Processing file00180.jpg
Processing file00341.jpg
Processing file00644.jpg
Processing file00479.jpg
Processing file00210.jpg
Processing file00291.jpg
Processing file00496.jpg
Processing file00663.jpg
Processing file00133.jpg
Processing file00536.jpg
Processing file00096.jpg
Processing file00616.jpg
Processing file00477.jpg
Processing file00387.jpg
Processing file00265.jpg
Processing file00422.jpg
Processing file00331.jpg
Processing file00179.jpg
Processing file00569.jpg
Processing file00687.jpg
Processing file00318.jpg
Processing file00564.jpg
Processing file00608.jpg
Processing file00075.jpg
Processing file00370.jpg
Processing file00508.jpg
Processing file00256.jpg
Processing file00545.jpg
Processing file00480.jpg
Processing file00284.jpg
Processing file00664.jpg
Processing file00411.jpg
Processing file00678.jpg
Processing file00029.jpg
Processing file00287.jpg
Processing file00316.jpg
Processing file00228.jpg
Processing file00208.jpg
Processing file00088.jpg
Processing file00182.jpg
Processing file00037.jpg
Processing file00510.jpg
Processing file00601.jpg
Processing file00326.jpg
Processing file00402.jpg
Processing file00610.jpg
Processing file00253.jpg
Processing file00430.jpg
Processing file00669.jpg
Processing file00573.jpg
Processing file00197.jpg
Processing file00621.jpg
Processing file00003.jpg
Processing file00641.jpg
Processing file00424.jpg
Processing file00649.jpg
Processing file00065.jpg
Processing file00281.jpg
Processing file00242.jpg
Processing file00699.jpg
Processing file00317.jpg
Processing file00650.jpg
Processing file00606.jpg
Processing file00247.jpg
Processing file00673.jpg
Processing file00351.jpg
Processing file00563.jpg
Processing file00447.jpg
Processing file00111.jpg
Processing file00701.jpg
Processing file00013.jpg
Processing file00507.jpg
Processing file00043.jpg
Processing file00622.jpg
Processing file00152.jpg
Processing file00523.jpg
Processing file00502.jpg
Processing file00270.jpg
Processing file00273.jpg
Processing file00512.jpg
Processing file00286.jpg
Processing file00497.jpg
Processing file00329.jpg
Processing file00659.jpg
Processing file00346.jpg
Processing file00476.jpg
Processing file00378.jpg
Processing file00328.jpg
Processing file00407.jpg
Processing file00108.jpg
Processing file00199.jpg
Processing file00685.jpg
Processing file00434.jpg
Processing file00335.jpg
Processing file00403.jpg
Processing file00436.jpg
Processing file00274.jpg
Processing file00034.jpg
Processing file00257.jpg
Processing file00369.jpg
Processing file00560.jpg
Processing file00250.jpg
Processing file00081.jpg
Processing file00109.jpg
Processing file00698.jpg
Processing file00143.jpg
Processing file00656.jpg
Processing file00213.jpg
Processing file00693.jpg
Processing file00655.jpg
Processing file00505.jpg
Processing file00360.jpg
Processing file00460.jpg
Processing file00016.jpg
Processing file00271.jpg
Processing file00155.jpg
Processing file00386.jpg
Processing file00359.jpg
Processing file00558.jpg
Processing file00243.jpg
Processing file00439.jpg
Processing file00347.jpg
Processing file00466.jpg
Processing file00557.jpg
Processing file00304.jpg
Processing file00379.jpg
Processing file00627.jpg
Processing file00237.jpg
Processing file00618.jpg
Processing file00567.jpg
Processing file00676.jpg
Processing file00305.jpg
Processing file00706.jpg
Processing file00151.jpg
Processing file00531.jpg
Processing file00139.jpg
Processing file00141.jpg
Processing file00516.jpg
Processing file00691.jpg
Processing file00166.jpg
Processing file00327.jpg
Processing file00104.jpg
Processing file00127.jpg
Processing file00014.jpg
Processing file00356.jpg
Processing file00532.jpg
Processing file00126.jpg
Processing file00409.jpg
Processing file00175.jpg
Processing file00249.jpg
Processing file00033.jpg
Processing file00216.jpg
Processing file00017.jpg
Processing file00176.jpg
Processing file00146.jpg
Processing file00010.jpg
Processing file00292.jpg
Processing file00220.jpg
Processing file00611.jpg
Processing file00072.jpg
Processing file00262.jpg
Processing file00481.jpg
Processing file00082.jpg
Processing file00525.jpg
Processing file00642.jpg
Processing file00435.jpg
Processing file00587.jpg
Processing file00185.jpg
Processing file00172.jpg
Processing file00288.jpg
Processing file00639.jpg
Processing file00489.jpg
Processing file00596.jpg
Processing file00586.jpg
Processing file00225.jpg
Processing file00425.jpg
Processing file00474.jpg
Processing file00392.jpg
Processing file00518.jpg
Processing file00441.jpg
Processing file00421.jpg
Processing file00004.jpg
Processing file00503.jpg
Processing file00704.jpg
Processing file00035.jpg
Processing file00493.jpg
Processing file00091.jpg
Processing file00027.jpg
Processing file00343.jpg
Processing file00620.jpg
Processing file00319.jpg
Processing file00051.jpg
Processing file00590.jpg
Processing file00241.jpg
Processing file00059.jpg
Processing file00070.jpg
Processing file00066.jpg
Processing file00158.jpg
Processing file00069.jpg
Processing file00540.jpg
Processing file00514.jpg
Processing file00672.jpg
Processing file00325.jpg
Processing file00485.jpg
Processing file00005.jpg
Processing file00134.jpg
Processing file00190.jpg
Processing file00588.jpg
Processing file00135.jpg
Processing file00138.jpg
Processing file00444.jpg
Processing file00145.jpg
Processing file00209.jpg
Processing file00278.jpg
Processing file00204.jpg
Processing file00012.jpg
Processing file00089.jpg
Processing file00320.jpg
Processing file00568.jpg
Processing file00117.jpg
Processing file00632.jpg
Processing file00350.jpg
Processing file00556.jpg
Processing file00079.jpg
Processing file00515.jpg
Processing file00196.jpg
Processing file00285.jpg
Processing file00074.jpg
Processing file00429.jpg
Processing file00511.jpg
Processing file00019.jpg
Processing file00554.jpg
Processing file00354.jpg
Processing file00348.jpg
Processing file00433.jpg
Processing file00660.jpg
Processing file00122.jpg
Processing file00307.jpg
Processing file00322.jpg
Processing file00188.jpg
Processing file00396.jpg
Processing file00283.jpg
Processing file00445.jpg
Processing file00332.jpg
Processing file00457.jpg
Processing file00290.jpg
Processing file00527.jpg
Processing file00559.jpg
Processing file00077.jpg
Processing file00310.jpg
Processing file00099.jpg
Processing file00214.jpg
Processing file00240.jpg
Processing file00314.jpg
Processing file00039.jpg
Processing file00428.jpg
Processing file00427.jpg
Processing file00463.jpg
Processing file00266.jpg
Processing file00309.jpg
Processing file00121.jpg
Processing file00614.jpg
Processing file00454.jpg
Processing file00694.jpg
Processing file00437.jpg
Processing file00279.jpg
Processing file00282.jpg
Processing file00275.jpg
Processing file00458.jpg
Processing file00103.jpg
Processing file00071.jpg
Processing file00619.jpg
Processing file00373.jpg
Processing file00630.jpg
Processing file00450.jpg
Processing file00068.jpg
Processing file00087.jpg
Processing file00565.jpg
Processing file00203.jpg
Processing file00259.jpg
Processing file00440.jpg
Processing file00388.jpg
Processing file00269.jpg
Processing file00006.jpg
Processing file00098.jpg
Processing file00353.jpg
Processing file00615.jpg
Processing file00539.jpg
Processing file00224.jpg
Processing file00045.jpg
Processing file00206.jpg
Processing file00100.jpg
Processing file00626.jpg
Processing file00277.jpg
Processing file00487.jpg
Processing file00374.jpg
Processing file00465.jpg
Processing file00086.jpg
Processing file00385.jpg
Processing file00692.jpg
Processing file00149.jpg
Processing file00420.jpg
Processing file00302.jpg
Processing file00695.jpg
Processing file00255.jpg
Processing file00657.jpg
Processing file00469.jpg
Processing file00689.jpg
Processing file00684.jpg
Processing file00591.jpg
Processing file00376.jpg
Processing file00298.jpg
Processing file00116.jpg
Processing file00150.jpg
Processing file00640.jpg
Processing file00235.jpg
Processing file00323.jpg
Processing file00334.jpg
Processing file00238.jpg
Processing file00110.jpg
Processing file00501.jpg
Processing file00651.jpg
Processing file00384.jpg
Processing file00040.jpg
Processing file00280.jpg
Processing file00308.jpg
Processing file00047.jpg
Processing file00364.jpg
Processing file00020.jpg
Processing file00112.jpg
Processing file00517.jpg
Processing file00340.jpg
Processing file00181.jpg
Processing file00119.jpg
Processing file00377.jpg
Processing file00471.jpg
Processing file00022.jpg
Processing file00636.jpg
Processing file00207.jpg
Processing file00193.jpg
Processing file00130.jpg
Processing file00535.jpg
Processing file00162.jpg
Processing file00094.jpg
Processing file00634.jpg
Processing file00389.jpg
Processing file00023.jpg
Processing file00631.jpg
Processing file00115.jpg
Processing file00529.jpg
Processing file00352.jpg
Processing file00211.jpg
Processing file00580.jpg
Processing file00397.jpg
Processing file00153.jpg
Processing file00101.jpg
Processing file00015.jpg
Processing file00602.jpg
Processing file00391.jpg
Processing file00049.jpg
Processing file00137.jpg
Processing file00289.jpg
Processing file00073.jpg
Processing file00254.jpg
Processing file00575.jpg
Processing file00604.jpg
Processing file00021.jpg
Processing file00577.jpg
Processing file00609.jpg
Processing file00357.jpg
Processing file00118.jpg
Processing file00061.jpg
Processing file00173.jpg
Processing file00410.jpg
Processing file00129.jpg
Processing file00030.jpg
Processing file00470.jpg
Processing file00063.jpg
Processing file00406.jpg
Processing file00008.jpg
Processing file00675.jpg
Processing file00336.jpg
Processing file00638.jpg
Processing file00349.jpg
Processing file00468.jpg
Processing file00381.jpg
Processing file00646.jpg
Processing file00552.jpg
Processing file00700.jpg
Processing file00702.jpg
Processing file00024.jpg
Processing file00499.jpg
Processing file00448.jpg
Processing file00106.jpg
Processing file00585.jpg
Processing file00574.jpg
Processing file00513.jpg
Processing file00338.jpg
Processing file00599.jpg
Processing file00578.jpg
Processing file00443.jpg
Processing file00426.jpg
Processing file00026.jpg
Processing file00703.jpg
Processing file00553.jpg
Processing file00227.jpg
Processing file00064.jpg
Processing file00519.jpg
Processing file00306.jpg
Processing file00371.jpg
Processing file00163.jpg
Processing file00398.jpg
Processing file00455.jpg
Processing file00661.jpg
Processing file00662.jpg
Processing file00431.jpg
Processing file00362.jpg
Processing file00449.jpg
Processing file00677.jpg
Processing file00055.jpg
Processing file00697.jpg
Processing file00653.jpg
Processing file00467.jpg
Processing file00683.jpg
Processing file00629.jpg
Processing file00400.jpg
Processing file00478.jpg
Processing file00067.jpg
Processing file00041.jpg
Processing file00296.jpg
Processing file00413.jpg
Processing file00680.jpg
Processing file00405.jpg
Processing file00625.jpg
Processing file00226.jpg
Processing file00233.jpg
Processing file00561.jpg
Processing file00494.jpg
Processing file00324.jpg
Processing file00628.jpg
Processing file00170.jpg
Processing file00222.jpg
Processing file00456.jpg
Processing file00363.jpg
Processing file00168.jpg
Processing file00202.jpg
Processing file00031.jpg
Processing file00538.jpg
Processing file00581.jpg
Processing file00593.jpg
Processing file00446.jpg
Processing file00453.jpg
Processing file00297.jpg
Processing file00159.jpg
Processing file00339.jpg
Processing file00414.jpg
Processing file00300.jpg
Processing file00452.jpg
Processing file00001.jpg
Processing file00028.jpg
Processing file00528.jpg
Processing file00060.jpg
Processing file00044.jpg
Processing file00092.jpg
Processing file00654.jpg
Processing file00483.jpg
Processing file00205.jpg
Processing file00194.jpg
Processing file00261.jpg
Processing file00219.jpg
Processing file00295.jpg
Processing file00102.jpgTraceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/utils/ipc/worker.py", line 216, in main
  File "calibre/gui2/convert/gui_conversion.py", line 41, in gui_convert_override
  File "calibre/gui2/convert/gui_conversion.py", line 28, in gui_convert
  File "calibre/ebooks/conversion/plumber.py", line 1105, in run
  File "calibre/customize/conversion.py", line 245, in __call__
  File "calibre_plugins.kindle_comics.__init__", line 41, in convert
  File "calibre_plugins.kindle_comics.make_book", line 28, in make_book
  File "calibre_plugins.kindle_comics.make_book", line 50, in sanitize_tree
  File "calibre_plugins.kindle_comics.make_book", line 73, in _slugify
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.__init__", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.slugify", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 192, in exec_module
  File "calibre_plugins.kindle_comics.kindle_comic_lib.text_unidecode.__init__", line 15, in <module>
  File "zipfile.py", line 1251, in __init__
NotADirectoryError: [Errno 20] N'est pas un dossier: '/home/user/.config/calibre/plugins/Kindle Comics Input.zip/kindle_comic_lib/text_unidecode/../..'

Processing file00344.jpg
Processing file00504.jpg
Processing file00156.jpg
Processing file00056.jpg
Processing file00566.jpg
Processing file00171.jpg
Processing file00688.jpg
Processing file00686.jpg
Processing file00395.jpg
Processing file00054.jpg
Processing file00248.jpg
Processing file00584.jpg
Processing file00423.jpg
Processing file00105.jpg
Processing file00668.jpg
Processing file00125.jpg
Processing file00589.jpg
Processing file00390.jpg
Processing file00482.jpg
Processing file00415.jpg
Processing file00160.jpg
Processing file00570.jpg
Processing file00267.jpg
Processing file00215.jpg
Processing file00367.jpg
Processing file00600.jpg
Processing file00198.jpg
Processing file00236.jpg
Processing file00057.jpg
Processing file00594.jpg
Processing file00293.jpg
Processing file00543.jpg
Processing file00264.jpg
Processing file00036.jpg
Processing file00113.jpg
Processing file00393.jpg
Processing file00550.jpg
Processing file00032.jpg
Processing file00246.jpg
Processing file00394.jpg
Processing file00095.jpg
Processing file00491.jpg
Processing file00509.jpg
Processing file00451.jpg
Processing file00195.jpg
Processing file00124.jpg
Processing file00572.jpg
Processing file00007.jpg
Processing file00313.jpg
Processing file00592.jpg
Processing file00416.jpg
Processing file00345.jpg
Processing file00011.jpg
Processing file00612.jpg
Processing file00488.jpg
Processing file00183.jpg
Processing file00546.jpg
Processing file00652.jpg
Processing file00366.jpg
Processing file00617.jpg
Processing file00093.jpg
Processing file00038.jpg
Processing file00682.jpg
Processing file00136.jpg
Processing file00666.jpg
Processing file00191.jpg
Processing file00522.jpg
Processing file00097.jpg
Processing file00177.jpg
Processing file00365.jpg
Processing file00025.jpg
Processing file00046.jpg
Processing file00500.jpg
Processing file00048.jpg
Processing file00408.jpg
Processing file00533.jpg
Processing file00050.jpg
Processing file00260.jpg
Processing file00486.jpg
Processing file00361.jpg
Processing file00583.jpg
Processing file00520.jpg
Processing file00679.jpg
Processing file00076.jpg
Processing file00128.jpg
Processing file00140.jpg
Processing file00132.jpg
Processing file00412.jpg
Processing file00382.jpg
Processing file00419.jpg
Processing file00084.jpg
Processing file00472.jpg
Processing file00258.jpg
Processing file00576.jpg
Processing file00276.jpg
Sanitizing tree...
```

**Comment by Bouilloire-dot** [comment]
I just noticed the issue was already reported. I'm new to github, sorry
